[package]
name = "sd-card-video-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.5"
tempfile = "3.2"
chrono = "0.4"
