name: Build SD Card Video Viewer

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || matrix.os == 'macos-latest' && 'x86_64-apple-darwin' || 'x86_64-unknown-linux-gnu' }}

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Install FFmpeg
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y ffmpeg
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew install ffmpeg
        fi
      shell: bash

    - name: Install FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install ffmpeg
      shell: powershell

    - name: Install npm dependencies
      run: npm install
      working-directory: .

    - name: Build Tauri app
      run: npm run tauri build
      working-directory: .
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sd-card-video-viewer-${{ matrix.os }}
        path: |
          src-tauri/target/release/bundle/**/*
        retention-days: 5
